### ISSUE TITLE
Compose: Unbound public symbols not allowed

### ISSUE THREAD

**Issue by noahjutz** [noahjutz/GymRoutines#28]
Migrating to compose is impossible due to an error.

### Stacktrace:
```
e: java.lang.AssertionError: Unbound symbols not allowed
	Unbound public symbol for public kotlinx.android.synthetic.main.activity_main/app_bar.<get-app_bar>|-6126882245708992258[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.activity_main/bottom_nav.<get-bottom_nav>|3614138208614755936[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.listitem_exercise.view/name.<get-name>|5834677513340743011[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.fragment_routines/recycler_view.<get-recycler_view>|5156468425898823808[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.fragment_routines/fab_pick_exercises.<get-fab_pick_exercises>|6066832289080247191[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.listitem_routine.view/name.<get-name>|5834677513340743011[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.fragment_create_routine/recycler_view.<get-recycler_view>|5156468425898823808[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.listitem_set.view/edit_reps.<get-edit_reps>|-359322958494366889[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.listitem_set.view/edit_weight.<get-edit_weight>|-7703905847042342814[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.listitem_set.view/edit_time.<get-edit_time>|4364912614072118262[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.listitem_set.view/edit_distance.<get-edit_distance>|2321864979190091302[0]
	Unbound public symbol for public kotlinx.android.synthetic.main.fragment_pick_exercise/recycler_view.<get-recycler_view>|5156468425898823808[0]
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:96)
	at org.jetbrains.kotlin.backend.jvm.JvmBackendFacade.doGenerateFiles(JvmBackendFacade.kt:87)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:40)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:616)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:203)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:346)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:102)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:240)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:39)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:81)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:601)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1633)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
### Affected views:
* activity_main/app_bar
activity_main/bottom_nav

* listitem_exercise.view/name

* fragment_routines/recycler_view
fragment_routines/fab_pick_exercises

* listitem_routine.view/name

* fragment_create_routine/recycler_view

* listitem_set.view/edit_reps
listitem_set.view/edit_weight
listitem_set.view/edit_time
listitem_set.view/edit_distance

* fragment_pick_exercise/recycler_view

### How to replicate bug:
Attempts:
- [x]  Migrating a regular project with XML layout to compose -> No
- [x]  Migrating a Kotlin DSL project with XML layout to compose -> No
- [x]  See what the affected views have in common -> ?

**Comment by noahjutz** [comment]
All affected views seem to have one thing in common: **They use view binding**
-> Next step: Test if a new project with view binding can use compose.

**Comment by noahjutz** [comment]
The views use **Kotlin synthetic binding**. (`kotlinx.android.synthetic`, plugin `kotlin-android-extensions`)

**Comment by noahjutz** [comment]
### How to replicate:
1. Create an empty activity project using android studio 4.2 canary 12
2. Add necessary dependencies:
* Compose: [link](https://developer.android.com/jetpack/compose/setup)
* Kotlin Synthetic Binding: Plugin `kotlin-android-extensions`
3. Up until now, everything still works. Try to build the project - should work.
4. Reference a view, importing `kotlinx.android.synthetic.main.activity_main.*`
5. Try to build project - should throw exception.

Stacktrace (example uses @+id/test)
```
> Task :app:compileDebugKotlin FAILED
e: java.lang.AssertionError: Unbound symbols not allowed
	Unbound public symbol for public kotlinx.android.synthetic.main.activity_main/test.<get-test>|631656647662068737[0]
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:96)
	at org.jetbrains.kotlin.backend.jvm.JvmBackendFacade.doGenerateFiles(JvmBackendFacade.kt:87)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:40)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:616)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:203)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:346)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:102)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:240)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:90)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:601)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1633)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by noahjutz** [comment]
Sample project: https://github.com/noahjutz/TestMigrateCompose
Google issuetracker: https://issuetracker.google.com/issues/169219044

**Comment by noahjutz** [comment]
Next step: Replace synthetic binding with [regular view binding](https://developer.android.com/topic/libraries/view-binding)

**Comment by noahjutz** [comment]
- [ ] activity_main/app_bar
- [ ] activity_main/bottom_nav
- [ ] listitem_exercise.view/name
- [ ] fragment_routines/recycler_view
- [ ] fragment_routines/fab_pick_exercises
- [ ] listitem_routine.view/name
- [ ] fragment_create_routine/recycler_view
- [ ] listitem_set.view/edit_reps
- [ ] listitem_set.view/edit_weight
- [ ] listitem_set.view/edit_time
- [ ] listitem_set.view/edit_distance
- [ ] fragment_pick_exercise/recycler_view

**Comment by noahjutz** [comment]
- [ ] ui.exercises.ExercisesAdapter.kt
- [ ] ui.exercises.create.CreateExerciseFragment.kt
- [ ] ui.exercises.ExercisesFragment.kt
- [ ] ui.routines.RoutinesFragment.kt
- [ ] ui.routines.RoutineAdapter.kt
- [ ] ui.routines.create.pick.ExercisesAdapter.kt
- [ ] ui.routines.create.pick.PickExerciseFragment.kt
- [ ] ui.routines.create.SetAdapter.kt
- [ ] ui.routines.create.CreateRoutineFragment.kt
- [ ] ui.MainActivity.kt

**Comment by noahjutz** [comment]
Instead of using normal view binding, just use findViewById for now: 80618351a3b04b5aed86ff22c52227cf16017e6c

**Comment by noahjutz** [comment]
Build passing with https://github.com/noahjutz/GymRoutines/commit/4360c0ead900432cb8bb2240554a6b0aea3da0fc, issue closed.
